lastupdatecheck: 0
recentrepos:
- /Users/rdayabhai/code/dotfiles
- /Users/rdayabhai/Dropbox/Education Resources/Misc-Exercism-Exercises
- /Users/rdayabhai/code/UPenn-CIS-194
- /Users/rdayabhai/Dropbox/Education Resources/MIT-6006
- /Users/rdayabhai/.config/nvim
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: true
